export interface movie {
    Cast: string,
    Detail: string,
    Disney: number,
    Genre: string,
    HBO: number,
    IsTrending: string,
    MovieID: string,
    MovieName: string,
    Netflix: number,
    Poster: string,
    Prime: number,
    Rating: string,
    ReleaseDate: string,
    createdAt: string,
    id: number,
    updatedAt: string,
    }